const INPUT_SIZE = 133;
const OUTPUT_SIZE = 36;
const COMMIT_WEIGHT = 400;
const REVEAL_WEIGHT = 200;
const TALLY_WEIGHT = 100;
const ALPHA = 1;
const BETA = 1;
const GAMMA = 10;

const KEYPATH_PURPOSE = 3.0;
const KEYPATH_COIN_TYPE = 4919.0;
const KEYPATH_ACCOUNT = 0.0;
const EXTERNAL_KEYCHAIN = 0;
const INTERNAL_KEYCHAIN = 1;
